import { experienceInsights } from "@/lib/training/insights";
import { describeMedicalStatus, medicalStatus } from "@/lib/medical/status";
import { trainingLocks } from "@/lib/medical/rehab";
import type { CombatExperience } from "@/lib/types";
import type { TrainingChicken } from "../types";

const EMPTY_EXPERIENCE:CombatExperience={offensive:0,defensive:0,evasion:0,counter:0,pressure:0,recovery:0,adaptation:0};
export function CoachReport({ chicken }: { chicken:TrainingChicken|null }) { if(!chicken)return null;const experience=chicken.experience??EMPTY_EXPERIENCE;const ordered=Object.entries(experience).sort((a,b)=>b[1]-a[1]);const insights=experienceInsights(experience);const active=(chicken.injuries??[]).filter(i=>i.permanent||i.recoveryRemaining>0);const locks=trainingLocks(active);const fatigue=chicken.trainingState?.trainingFatigue??0;const recommendation=insights[0]?.recommendedTraining??(fatigue>60?"recovery":chicken.fightingStyle==="counter"?"technique":chicken.fightingStyle==="endurance"?"stamina":"strength");
  return <section className="smoked-glass-light rounded-xl p-4"><div className="flex items-center justify-between"><h3 className="font-display text-sm text-(--color-gold-bright)">Coach Report</h3><span className="text-[9px] uppercase tracking-wider text-(--color-text-muted)">{describeMedicalStatus(medicalStatus(chicken))}</span></div><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><p className="text-[9px] font-bold uppercase tracking-wider text-emerald-300/75">Strengths</p><p className="mt-1 capitalize text-(--color-parchment)">{ordered.slice(0,2).map(([k])=>k).join(" · ")||"Still developing"}</p></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-amber-300/75">Development gaps</p><p className="mt-1 capitalize text-(--color-parchment)">{insights.slice(0,2).map(i=>i.weakCategory).join(" · ")||ordered.slice(-2).map(([k])=>k).join(" · ")}</p></div></div><div className="mt-3 border-t border-(--color-gold)/10 pt-3"><p className="text-[9px] font-bold uppercase tracking-wider text-(--color-gold-bright)">Recommendation</p><p className="mt-1 text-xs text-(--color-parchment)"><span className="capitalize">{recommendation}</span> work {fatigue>60?"will keep load controlled while fatigue recedes.":"best supports the fighter's current development profile."}</p>{locks.size>0&&<p className="mt-2 text-[10px] text-amber-200">Current injuries restrict {Array.from(locks).join(", ")} work.</p>}{fatigue>=70&&<p className="mt-2 text-[10px] text-red-200">Heavy training load: use Light intensity or recovery work until fatigue drops.</p>}</div></section>;
}
