import { describeMedicalStatus, medicalStatus, medicalStatusTone } from "@/lib/medical/status";
import type { TrainingChicken } from "../types";

function Meter({ label, value, inverse=false }: { label:string; value:number; inverse?:boolean }) { const tone=inverse?(value>70?"bg-red-400":value>40?"bg-amber-400":"bg-emerald-400"):(value<35?"bg-red-400":value<65?"bg-amber-400":"bg-emerald-400");return <div><div className="mb-1 flex justify-between text-[10px] uppercase tracking-wider text-(--color-text-muted)"><span>{label}</span><b className="text-(--color-parchment)">{Math.round(value)}</b></div><div className="h-1.5 overflow-hidden rounded bg-black/50"><span className={`block h-full rounded ${tone}`} style={{width:`${Math.max(0,Math.min(100,value))}%`}} /></div></div>; }

export function FighterDevelopmentPanel({ chicken }: { chicken:TrainingChicken|null }) {
  if(!chicken)return <aside className="smoked-glass rounded-xl p-4 text-sm text-(--color-text-muted)">Select a fighter to begin coaching.</aside>;
  const development=chicken.trainingDevelopment;const specializations=Object.entries(development?.specializationProgress??{}).sort((a,b)=>b[1]-a[1]);const lead=specializations[0];const status=medicalStatus(chicken);const tone=medicalStatusTone(status);
  return <aside className="smoked-glass rounded-xl p-4"><p className="text-[9px] font-bold uppercase tracking-[.22em] text-(--color-gold-bright)">Selected fighter</p><h2 className="mt-1 font-display text-xl text-(--color-parchment)">{chicken.name}</h2><p className="text-[10px] uppercase tracking-wider text-(--color-text-muted)">{chicken.growthStage} · {chicken.fightingStyle} style</p>
    {lead&&<div className="mt-4 rounded-lg border border-(--color-gold)/15 bg-black/25 p-3"><div className="flex justify-between text-xs"><span className="capitalize text-(--color-parchment)">{lead[0]} specialist</span><b className="text-(--color-gold-bright)">{Math.min(100,Math.round(lead[1]))}%</b></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-black/50"><span className="block h-full bg-gradient-to-r from-(--color-gold) to-(--color-gold-bright)" style={{width:`${Math.min(100,lead[1])}%`}} /></div></div>}
    <div className="mt-4 space-y-3"><Meter label="Condition" value={chicken.condition??100} /><Meter label="Energy" value={chicken.energy} /><Meter label="Training fatigue" value={chicken.trainingState?.trainingFatigue??0} inverse /><Meter label="Stress" value={chicken.stress??0} inverse /></div>
    <div className={`mt-4 rounded border px-3 py-2 text-xs ${tone==="ok"?"border-emerald-400/20 bg-emerald-950/25 text-emerald-200":tone==="warn"?"border-amber-400/20 bg-amber-950/25 text-amber-200":"border-red-400/20 bg-red-950/25 text-red-200"}`}><span className="block text-[9px] font-bold uppercase tracking-wider opacity-70">Medical status</span>{describeMedicalStatus(status)}</div>
    {specializations.length>1&&<div className="mt-4 border-t border-(--color-gold)/10 pt-3"><p className="text-[9px] font-bold uppercase tracking-wider text-(--color-text-muted)">Fighter identity</p><div className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1">{specializations.slice(0,6).map(([name,value])=><div key={name} className="flex justify-between text-[10px]"><span className="capitalize text-(--color-text-muted)">{name}</span><span>{Math.round(value)}</span></div>)}</div></div>}
  </aside>;
}
