import { TRAINING_PROGRAMS } from "@/lib/facilities/config";
import type { ProgramDefinition, ProgramId } from "@/lib/facilities/types";
import type { TrainingCategory } from "@/lib/types";
import type { TrainingUiCategory } from "./TrainingCategoryTabs";

function uiCategory(program:ProgramDefinition):TrainingUiCategory { if(program.tags.includes("sparring"))return "sparring";if(program.category==="stamina"||program.category==="recovery")return "conditioning";if(program.category==="defense"||program.category==="discipline"||program.tags.includes("pressure")||program.category==="custom")return "tactical";if(program.category==="technique"||program.category==="agility")return "technique";return "physical"; }
function StatTags({ program }: { program:ProgramDefinition }) { const stats=[...Object.entries(program.primaryStats).map(([k,v])=>`${k} ${"+".repeat(Math.max(1,Math.round(v*4)))}`),...Object.keys(program.experienceGain??{}).slice(0,2).map(k=>`${k} XP`)];return <p className="mt-3 text-[10px] capitalize text-(--color-gold-bright)/80">{stats.join(" · ")}</p>; }
export function TrainingProgramGrid({ category, selectedId, facilityLevel, lockedCategories, customCategory, onSelect }: { category:TrainingUiCategory; selectedId:ProgramId|null; facilityLevel:number; lockedCategories:Set<TrainingCategory>; customCategory:TrainingCategory; onSelect:(id:ProgramId)=>void }) { const programs=Object.values(TRAINING_PROGRAMS).filter(program=>uiCategory(program)===category);return <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{programs.map(program=>{const facilityLocked=program.requiredFacilityLevel>facilityLevel;const trainingCategory=program.category==="custom"?customCategory:program.category;const injuryLocked=lockedCategories.has(trainingCategory);const selected=selectedId===program.id;return <button key={program.id} onClick={()=>onSelect(program.id)} className={`group rounded-xl border p-3 text-left transition ${selected?"border-(--color-gold-bright) bg-(--color-gold)/14 shadow-[0_0_24px_rgba(212,162,78,.08)]":"border-(--color-gold)/15 bg-black/25 hover:border-(--color-gold)/45"} ${facilityLocked||injuryLocked?"opacity-55":""}`}>
  <div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-sm text-(--color-parchment)">{program.name}</h3><p className="mt-1 text-[11px] leading-relaxed text-(--color-text-muted)">{program.description}</p></div><span className="text-lg text-(--color-gold-bright)">{program.tags.includes("sparring")?"⚔":program.category==="stamina"?"◌":program.category==="technique"?"◎":"◆"}</span></div><StatTags program={program} /><div className="mt-3 flex gap-3 text-[9px] uppercase tracking-wide text-(--color-text-muted)"><span>{program.durationMinutes}m</span><span>⚡ {program.energyCost}</span><span>Load {program.fatigueCost}</span></div>{facilityLocked&&<p className="mt-2 text-[10px] text-amber-200">Requires Fighter Camp Lv.{program.requiredFacilityLevel}</p>}{injuryLocked&&<p className="mt-2 text-[10px] text-red-200">Restricted by current injury</p>}</button>;})}</div>; }
