"use client";

import { TRAINING_PROGRAMS } from "@/lib/facilities/config";
import type { ProgramId } from "@/lib/facilities/types";
import { TRAINING_CATEGORIES, type TrainingCategory } from "@/lib/types";
import type { TrainingChicken, TrainingPreviewDTO } from "../types";

const INTENSITIES=["light","normal","hard","extreme"] as const;
export function TrainingSetupPanel({ chicken, programId, intensity, customCategory, preview, loading, disabledReason, onIntensity, onCustomCategory, onStart }: { chicken:TrainingChicken|null; programId:ProgramId|null; intensity:(typeof INTENSITIES)[number]; customCategory:TrainingCategory; preview:TrainingPreviewDTO|null; loading:boolean; disabledReason?:string|null; onIntensity:(value:(typeof INTENSITIES)[number])=>void; onCustomCategory:(value:TrainingCategory)=>void; onStart:()=>void }) {
  if(!programId)return <section className="smoked-glass rounded-xl p-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-(--color-gold-bright)">Training setup</p><p className="mt-2 text-sm text-(--color-text-muted)">Choose a program to move the camera to its station and review the exact server projection.</p></section>;
  const program=TRAINING_PROGRAMS[programId];return <section className="smoked-glass rounded-xl p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-(--color-gold-bright)">Training setup</p><h2 className="mt-1 font-display text-lg text-(--color-parchment)">{program.name}</h2></div><span className="rounded-full border border-(--color-gold)/20 bg-black/30 px-3 py-1 text-[9px] uppercase tracking-wider text-(--color-text-muted)">{program.durationMinutes} min</span></div>
    {program.category==="custom"&&<label className="mt-4 block text-[10px] uppercase tracking-wider text-(--color-text-muted)">Training focus<select value={customCategory} onChange={e=>onCustomCategory(e.target.value as TrainingCategory)} className="mt-1 block w-full rounded border border-(--color-gold)/20 bg-[#18110b] px-3 py-2 text-xs text-(--color-parchment)">{TRAINING_CATEGORIES.map(category=><option key={category} value={category}>{category}</option>)}</select></label>}
    <div className="mt-4"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-(--color-text-muted)">Intensity</p><div className="mt-2 grid grid-cols-4 gap-1">{INTENSITIES.map(option=><button key={option} onClick={()=>onIntensity(option)} className={`rounded border px-2 py-2 text-[9px] font-bold uppercase tracking-wide ${option===intensity?"border-(--color-gold-bright) bg-(--color-gold)/15 text-(--color-gold-bright)":"border-white/10 bg-black/25 text-(--color-text-muted)"}`}>{option}</button>)}</div></div>
    <div className="mt-4 min-h-36 rounded-lg border border-(--color-gold)/12 bg-black/25 p-3"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-(--color-gold-bright)">Expected development</p>{loading?<p className="mt-3 text-xs text-(--color-text-muted)">Coach is calculating the session...</p>:preview?<><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(preview.expectedEv).map(([stat,range])=>{const before=chicken?.ev[stat as keyof typeof chicken.ev]??0;return <div key={stat} className="flex justify-between text-xs"><span className="capitalize text-(--color-text-muted)">{stat} EV</span><span>{before.toFixed(1)} → {(before+range.min).toFixed(1)}–{(before+range.max).toFixed(1)}</span></div>;})}{Object.entries(preview.expectedExperience).map(([stat,range])=><div key={stat} className="flex justify-between text-xs"><span className="capitalize text-(--color-text-muted)">{stat} XP</span><span>+{range.min.toFixed(1)}–{range.max.toFixed(1)}</span></div>)}</div><div className="mt-3 grid grid-cols-3 gap-2 border-t border-(--color-gold)/10 pt-3 text-center"><Metric label="Efficiency" value={`${Math.round(preview.trainingEfficiency*100)}%`} /><Metric label="Breakthrough" value={`${(preview.estimatedBreakthroughChance*100).toFixed(1)}%`} /><Metric label="Injury risk" value={`${(preview.injuryRisk*100).toFixed(1)}%`} /></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-(--color-text-muted)"><span>Energy −{preview.energyCost}</span><span>Points −{preview.trainingPointCost}</span><span>Fatigue +{preview.fatigueGain}</span><span>Stress {signed(preview.stressChange)}</span><span>Condition {signed(preview.conditionChange)}</span></div></>:<p className="mt-3 text-xs text-(--color-text-muted)">Select an eligible fighter to request a preview.</p>}</div>
    {disabledReason&&<p className="mt-3 rounded border border-amber-300/20 bg-amber-950/25 px-3 py-2 text-xs text-amber-100">{disabledReason}</p>}
    <button onClick={onStart} disabled={!preview||loading||Boolean(disabledReason)} className="mt-4 w-full rounded-lg bg-gradient-to-b from-(--color-gold-bright) to-(--color-gold) px-4 py-3 font-display text-xs font-bold uppercase tracking-[.14em] text-(--color-ink) transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-45">Start training</button>
  </section>;
}
function Metric({label,value}:{label:string;value:string}){return <div><span className="block text-[9px] uppercase tracking-wide text-(--color-text-muted)">{label}</span><b className="text-xs text-(--color-parchment)">{value}</b></div>}
function signed(value:number){return `${value>=0?"+":""}${value}`;}
