"use client";

import { TRAINING_PROGRAMS } from "@/lib/facilities/config";
import type { TrainingResult } from "@/lib/training/types";

const pretty=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
export function TrainingCompletionModal({ result, onClose }: { result:TrainingResult|null; onClose:()=>void }) { if(!result)return null;const program=TRAINING_PROGRAMS[result.programId];return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className={`postfight-glass max-h-[90vh] w-full max-w-3xl overflow-y-auto ${result.breakthrough?"shadow-[0_0_80px_rgba(240,198,116,.2)]":""}`}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-(--color-gold-bright)">{result.breakthrough?"Breakthrough":"Training complete"}</p><h2 className="mt-2 font-display text-2xl text-(--color-parchment)">{program?.name??result.summary.headline}</h2><p className="mt-1 text-xs capitalize text-(--color-text-muted)">{result.intensity} intensity · {Math.round(result.trainingEfficiency*100)}% efficiency</p></div><button onClick={onClose} className="rounded-full border border-white/10 px-3 py-2 text-xs text-(--color-text-muted)">Close</button></div>
  {result.breakthrough&&<section className="mt-5 rounded-xl border border-(--color-gold-bright)/35 bg-(--color-gold)/12 p-4"><p className="text-[9px] font-bold uppercase tracking-[.2em] text-(--color-gold-bright)">Development breakthrough · {pretty(result.breakthrough.tag)}</p><p className="mt-2 text-sm text-(--color-parchment)">{result.breakthrough.message}</p>{result.breakthrough.traitUnlocked&&<p className="mt-2 text-xs text-(--color-gold-bright)">New trait: {result.breakthrough.traitUnlocked.name}</p>}</section>}
  <div className="mt-5 grid gap-4 md:grid-cols-2"><ResultGroup title="Physical development" values={result.statChanges} suffix=" EV" /><ResultGroup title="Combat development" values={result.experienceChanges} suffix=" XP" /><ResultGroup title="Behavior changes" values={result.behaviorChanges} decimals={4} /><ResultGroup title="Specialization progress" values={result.specializationProgressChanges} suffix="%" /></div>
  {Object.keys(result.effectiveStatChanges).length>0&&<section className="mt-4 rounded-xl border border-white/8 bg-black/20 p-4"><h3 className="text-[9px] font-bold uppercase tracking-[.18em] text-(--color-gold-bright)">Effective combat stats</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(result.effectiveStatChanges).map(([name,change])=><p key={name} className="flex justify-between text-xs"><span className="capitalize text-(--color-text-muted)">{name}</span><span>{change.before.toFixed(1)} → {change.after.toFixed(1)} <b className="ml-2 text-emerald-300">+{change.delta.toFixed(1)}</b></span></p>)}</div></section>}
  <section className="mt-4 rounded-xl border border-white/8 bg-black/20 p-4"><h3 className="text-[9px] font-bold uppercase tracking-[.18em] text-(--color-gold-bright)">Readiness & resources</h3><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs">{Object.entries(result.resourceChanges).map(([name,value])=><span key={name}><span className="capitalize text-(--color-text-muted)">{pretty(name)} </span><b className={value>0&&name!=="trainingFatigue"?"text-emerald-300":"text-amber-200"}>{value>=0?"+":""}{value.toFixed(1)}</b></span>)}</div></section>
  {result.potentialDiscovery&&<section className="mt-4 rounded-xl border border-sky-300/20 bg-sky-950/20 p-4"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-sky-200">Development insight</p><h3 className="mt-1 font-display text-lg text-(--color-parchment)">{result.potentialDiscovery.band} {pretty(result.potentialDiscovery.stat)} Aptitude</h3><p className="mt-2 text-xs text-(--color-text-muted)">{result.potentialDiscovery.message}</p></section>}
  {result.injury?<section className="mt-4 rounded-xl border border-red-300/25 bg-red-950/25 p-4"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-red-200">Training injury</p><h3 className="mt-1 font-display text-lg text-red-100">{result.injury.label}</h3><p className="mt-1 text-xs text-red-100/70">{pretty(result.injury.severity)} · recovery {result.injury.recoveryRemaining} cycles</p></section>:<p className="mt-4 text-xs text-emerald-300">● Session completed without injury.</p>}
  <button onClick={onClose} className="mt-6 w-full rounded-lg bg-gradient-to-b from-(--color-gold-bright) to-(--color-gold) px-4 py-3 font-display text-xs font-bold uppercase tracking-wider text-(--color-ink)">Continue coaching</button></div></div>; }
function ResultGroup({title,values,suffix="",decimals=2}:{title:string;values:Record<string,number>;suffix?:string;decimals?:number}){return <section className="rounded-xl border border-white/8 bg-black/20 p-4"><h3 className="text-[9px] font-bold uppercase tracking-[.18em] text-(--color-gold-bright)">{title}</h3>{Object.keys(values).length?<div className="mt-3 space-y-2">{Object.entries(values).map(([name,value])=><p key={name} className="flex justify-between text-xs"><span className="capitalize text-(--color-text-muted)">{pretty(name)}</span><b className="text-emerald-300">{value>=0?"+":""}{value.toFixed(decimals)}{suffix}</b></p>)}</div>:<p className="mt-2 text-xs text-(--color-text-muted)">No change.</p>}</section>}
