"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";

import { TRAINING_GYM_UPGRADES, TRAINING_PROGRAMS } from "@/lib/facilities/config";
import type { ProgramId } from "@/lib/facilities/types";
import { trainingLocks } from "@/lib/medical/rehab";
import type { TrainingCategory } from "@/lib/types";
import type { TrainingResult } from "@/lib/training/types";
import type { TrainingStationDefinition } from "@/lib/training/visuals/types";
import { TrainingScene3D } from "./scene/TrainingScene3D";
import type { FacilityViewDTO, SessionDTO, TrainingChicken, TrainingPreviewDTO } from "./types";
import { ActiveTrainingPanel } from "./ui/ActiveTrainingPanel";
import { CoachReport } from "./ui/CoachReport";
import { FighterDevelopmentPanel } from "./ui/FighterDevelopmentPanel";
import { FighterSelector } from "./ui/FighterSelector";
import { TrainingCategoryTabs, type TrainingUiCategory } from "./ui/TrainingCategoryTabs";
import { TrainingCompletionModal } from "./ui/TrainingCompletionModal";
import { TrainingProgramGrid } from "./ui/TrainingProgramGrid";
import { TrainingSetupPanel } from "./ui/TrainingSetupPanel";

const ERROR_MESSAGES:Record<string,string>={
  PROGRAM_LOCKED:"Upgrade the Fighter Camp to unlock this program.",INSUFFICIENT_ENERGY:"This fighter needs more energy before training.",TRAINING_LIMIT_REACHED:"This fighter has used its available training points.",TRAINING_LOCKED_BY_INJURY:"A current injury prevents this type of training.",FACILITY_CAPACITY_FULL:"All training slots are occupied.",CHICKEN_ALREADY_TRAINING:"This fighter already has an active session.",CHICKEN_NOT_ELIGIBLE:"This fighter is not at a trainable growth stage.",CONDITION_TOO_LOW:"Condition is too low for high-intensity training.",INSUFFICIENT_RESOURCES:"You do not have enough credits for this upgrade.",INVALID_INTENSITY:"That training intensity is unavailable.",SESSION_NOT_ACTIVE:"That session has already ended.",
};
const friendlyError=(value:unknown)=>ERROR_MESSAGES[String(value)]??"The camp could not complete that request. Please try again.";

export function TrainingGymShell() {
  const searchParams=useSearchParams();const requestedId=searchParams.get("chickenId")??"";
  const [facility,setFacility]=useState<FacilityViewDTO|null>(null);const [sessions,setSessions]=useState<SessionDTO[]>([]);const [chickens,setChickens]=useState<TrainingChicken[]>([]);const [selectedChickenId,setSelectedChickenId]=useState(requestedId);const [selectedProgramId,setSelectedProgramId]=useState<ProgramId|null>(null);const [category,setCategory]=useState<TrainingUiCategory>("physical");const [intensity,setIntensity]=useState<"light"|"normal"|"hard"|"extreme">("normal");const [customCategory,setCustomCategory]=useState<TrainingCategory>("strength");const [preview,setPreview]=useState<{key:string;data:TrainingPreviewDTO}|null>(null);const [previewLoading,setPreviewLoading]=useState(false);const [error,setError]=useState<string|null>(null);const [completion,setCompletion]=useState<TrainingResult|null>(null);const [refreshing,setRefreshing]=useState(true);
  const initialized=useRef(false),activeIds=useRef(new Set<string>()),completedIds=useRef(new Set<string>());

  const refresh=useCallback(async()=>{try{const [facilityRes,chickensRes]=await Promise.all([fetch("/api/facilities",{cache:"no-store"}),fetch("/api/chickens",{cache:"no-store"})]);if(!facilityRes.ok||!chickensRes.ok)throw new Error("LOAD_FAILED");const body=await facilityRes.json() as {facility:FacilityViewDTO;activeSessions:SessionDTO[];completedSessions:SessionDTO[]};const roster=await chickensRes.json() as TrainingChicken[];
    if(initialized.current){const newlyCompleted=body.completedSessions.find(session=>activeIds.current.has(session.id)&&!completedIds.current.has(session.id)&&session.adaptationResult);if(newlyCompleted?.adaptationResult)setCompletion(newlyCompleted.adaptationResult);}else initialized.current=true;
    activeIds.current=new Set(body.activeSessions.map(session=>session.id));completedIds.current=new Set(body.completedSessions.map(session=>session.id));setFacility(body.facility);setSessions(body.activeSessions);setChickens(roster);setSelectedChickenId(current=>current&&roster.some(chicken=>chicken.id===current)?current:(roster.find(chicken=>chicken.sex==="rooster")??roster[0])?.id??"");setRefreshing(false);
  }catch{setError("The Fighter Camp could not be loaded.");setRefreshing(false);}},[]);

  useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10_000);return()=>clearInterval(timer);},[refresh]);
  const selected=chickens.find(chicken=>chicken.id===selectedChickenId)??null;const selectedSession=sessions.find(session=>session.chickenId===selectedChickenId);const injuries=(selected?.injuries??[]).filter(injury=>injury.permanent||injury.recoveryRemaining>0);const locks=useMemo(()=>trainingLocks(injuries),[injuries]);const program=selectedProgramId?TRAINING_PROGRAMS[selectedProgramId]:null;const resolvedCategory=program?.category==="custom"?customCategory:program?.category;const facilityUnlocked=Boolean(program&&facility&&program.requiredFacilityLevel<=facility.level);const injuryLocked=Boolean(resolvedCategory&&locks.has(resolvedCategory));

  const previewRequestKey=selected&&program?`${selected.id}:${program.id}:${intensity}:${program.category==="custom"?customCategory:"fixed"}`:"";
  useEffect(()=>{if(!selected||!program||!facilityUnlocked||injuryLocked||selectedSession)return;const controller=new AbortController();const timer=setTimeout(async()=>{setPreviewLoading(true);try{const payload:Record<string,string>={chickenId:selected.id,programId:program.id,intensity};if(program.category==="custom")payload.category=customCategory;const response=await fetch("/api/training-sessions/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error);setPreview({key:previewRequestKey,data:body});}catch(reason){if(!controller.signal.aborted)setError(friendlyError(reason instanceof Error?reason.message:reason));}finally{if(!controller.signal.aborted)setPreviewLoading(false);}},180);return()=>{clearTimeout(timer);controller.abort();};},[selected,program,intensity,customCategory,facilityUnlocked,injuryLocked,selectedSession,previewRequestKey]);

  function chooseFighter(id:string){setSelectedChickenId(id);const session=sessions.find(item=>item.chickenId===id);if(session){setSelectedProgramId(session.programId);setIntensity(session.intensity);}}
  function chooseProgram(id:ProgramId){setSelectedProgramId(id);setError(null);}
  function stationSelect(station:TrainingStationDefinition){const candidate=station.programs.find(id=>(TRAINING_PROGRAMS[id]?.requiredFacilityLevel??99)<=(facility?.level??0))??station.programs[0];if(candidate)chooseProgram(candidate);}
  async function start(){if(!selected||!program)return;setError(null);const payload:Record<string,string>={chickenId:selected.id,programId:program.id,intensity};if(program.category==="custom")payload.category=customCategory;const response=await fetch("/api/training-sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok){setError(friendlyError(body.error));return;}await refresh();}
  async function cancel(sessionId:string){setError(null);const response=await fetch(`/api/training-sessions/${sessionId}/cancel`,{method:"POST"});if(!response.ok){const body=await response.json();setError(friendlyError(body.error));return;}await refresh();}
  async function upgrade(){if(!facility)return;setError(null);const response=await fetch(`/api/facilities/${facility.id}/upgrade`,{method:"POST"});if(!response.ok){const body=await response.json();setError(friendlyError(body.error));return;}await refresh();}

  const validPreview=preview?.key===previewRequestKey?preview.data:null;
  const disabledReason=!selected?"Select a fighter first.":selectedSession?"This fighter is already training.":!facilityUnlocked?`Requires Fighter Camp Lv.${program?.requiredFacilityLevel}.`:injuryLocked?"A current injury restricts this training category.":facility&&sessions.length>=facility.capacity?"All training slots are occupied.":validPreview&&selected.energy<validPreview.energyCost?"This fighter needs more energy.":validPreview&&(selected.trainingState?.trainingPoints??100)<validPreview.trainingPointCost?"Not enough training points remain.":null;
  if(!facility)return <main className="min-h-screen bg-[#0d0a07] p-4"><div className="mx-auto max-w-[1500px]"><div className="smoked-glass h-[68vh] min-h-[520px] animate-pulse rounded-2xl"><p className="p-6 font-display text-sm text-(--color-gold-bright)">{refreshing?"Opening Fighter Camp…":"Fighter Camp unavailable"}</p></div></div></main>;
  const nextCost=TRAINING_GYM_UPGRADES[facility.level+1]?.cost;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_50%_0%,#2b2115_0%,#0d0a07_55%)] px-3 py-4 sm:px-5 lg:px-7"><div className="mx-auto max-w-[1500px]">
    <header className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><Link href="/coop" className="text-[10px] font-bold uppercase tracking-[.16em] text-(--color-gold-bright)">← Back to Coop</Link><p className="mt-3 text-[9px] font-bold uppercase tracking-[.26em] text-(--color-text-muted)">Training Gym · Level {facility.level}</p><h1 className="font-display text-2xl text-(--color-parchment) sm:text-3xl">Fighter Camp</h1></div><div className="flex flex-wrap items-center gap-2"><FacilityMetric label="Training slots" value={`${sessions.length} / ${facility.capacity}`} /><FacilityMetric label="Efficiency" value={`${Math.round(facility.efficiency*100)}%`} /><FacilityMetric label="Combat XP" value={`+${Math.round((facility.experienceMultiplier-1)*100)}%`} />{nextCost&&<button onClick={upgrade} className="rounded-lg border border-(--color-gold)/30 bg-(--color-gold)/10 px-3 py-2 text-left"><span className="block text-[8px] uppercase tracking-wider text-(--color-text-muted)">Upgrade to Lv.{facility.level+1}</span><b className="text-xs text-(--color-gold-bright)">{nextCost.toLocaleString()} credits</b></button>}</div></header>
    {error&&<div className="mb-3 flex items-center justify-between rounded-lg border border-red-300/20 bg-red-950/35 px-4 py-3 text-xs text-red-100"><span>{error}</span><button onClick={()=>setError(null)} aria-label="Dismiss">×</button></div>}
    <FighterSelector chickens={chickens} sessions={sessions} selectedId={selectedChickenId} onSelect={chooseFighter} />
    <div className="mt-3 grid gap-3 xl:grid-cols-[minmax(0,1fr)_20rem]"><section className="smoked-glass relative min-h-[520px] overflow-hidden rounded-2xl"><TrainingScene3D level={facility.level} chickens={chickens} sessions={sessions} selectedChickenId={selectedChickenId} selectedProgramId={selectedProgramId} onStationSelect={stationSelect} /><div className="pointer-events-none absolute inset-x-3 top-3 flex justify-between gap-2"><span className="rounded-full border border-(--color-gold)/20 bg-black/55 px-3 py-1.5 text-[9px] uppercase tracking-wider text-(--color-parchment) backdrop-blur">Static bird&apos;s-eye camp · drag to pan · scroll to zoom</span>{selectedSession&&<span className="rounded-full border border-emerald-300/20 bg-emerald-950/50 px-3 py-1.5 text-[9px] uppercase tracking-wider text-emerald-200 backdrop-blur">● Server session active</span>}</div></section><div className="space-y-3"><FighterDevelopmentPanel chicken={selected} /><CoachReport chicken={selected} /><ActiveTrainingPanel sessions={sessions} chickens={chickens} capacity={facility.capacity} selectedChickenId={selectedChickenId} onSelect={chooseFighter} onCancel={cancel} /></div></div>
    <section className="smoked-glass mt-3 rounded-2xl p-2 sm:p-3"><TrainingCategoryTabs value={category} onChange={setCategory} /><div className="mt-3"><TrainingProgramGrid category={category} selectedId={selectedProgramId} facilityLevel={facility.level} lockedCategories={locks} customCategory={customCategory} onSelect={chooseProgram} /></div></section>
    <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1fr)_24rem]"><div className="smoked-glass-light rounded-xl p-4"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-(--color-gold-bright)">Camp notes</p><p className="mt-2 text-sm leading-relaxed text-(--color-text-muted)">Select a program to focus its physical station. Training visuals are cosmetic; timing, progression, risk, injuries, and rewards remain server-authoritative and continue while you are away.</p></div><TrainingSetupPanel chicken={selected} programId={selectedProgramId} intensity={intensity} customCategory={customCategory} preview={validPreview} loading={previewLoading} disabledReason={disabledReason} onIntensity={setIntensity} onCustomCategory={setCustomCategory} onStart={start} /></div>
  </div><TrainingCompletionModal result={completion} onClose={()=>setCompletion(null)} /></main>;
}
function FacilityMetric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-(--color-gold)/20 bg-black/35 px-3 py-2"><span className="block text-[8px] uppercase tracking-wider text-(--color-text-muted)">{label}</span><b className="text-xs text-(--color-parchment)">{value}</b></div>}
