"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ChickenThumbnail } from "@/components/chicken3d/ChickenThumbnail";
import { TournamentAction, TournamentShell } from "@/components/tournament/TournamentShell";
import { TOURNAMENT_DEFINITIONS, type TournamentDefinition } from "@/lib/tournament";
import type { Chicken } from "@/lib/types";

type CircuitStep = "circuit" | "details" | "registration" | "confirm";
function eligibility(chicken: Chicken): string | null { if (chicken.sex !== "rooster") return "Hens cannot enter"; if (chicken.injured) return "Injured"; if (chicken.status !== "active") return "Not active"; return null; }

function EventPoster({ event, onView }: { event: TournamentDefinition; onView: () => void }) {
  const locked = Boolean(event.qualification);
  return <article className={`tournament-panel group relative overflow-hidden p-5 ${locked ? "opacity-55" : "hover:border-(--color-gold)/55"}`}><div className="absolute inset-0 bg-[linear-gradient(110deg,rgba(113,67,21,.18),transparent_55%,rgba(0,0,0,.35))]" /><div className="relative"><div className="flex items-start justify-between gap-4"><div><p className="tournament-kicker">{event.circuit} circuit</p><h2 className="mt-2 font-display text-2xl text-(--color-parchment)">{event.name}</h2></div><span className="rounded-full border border-(--color-gold)/35 px-2 py-1 text-[9px] font-bold uppercase tracking-[.14em] text-(--color-gold-bright)">{locked ? "Locked" : event.tier}</span></div><div className="mt-8 flex items-end justify-between border-y border-(--color-gold)/15 py-3"><p className="text-xs text-(--color-parchment)"><b className="block text-[9px] uppercase tracking-[.16em] text-(--color-text-muted)">Format</b>{event.bracketSize} fighters · elimination</p><p className="text-right text-xs text-(--color-parchment)"><b className="block text-[9px] uppercase tracking-[.16em] text-(--color-text-muted)">Champion prize</b>{event.championPrize.toLocaleString()} tokens</p></div><p className="mt-3 min-h-8 text-xs text-(--color-text-muted)">{event.qualification ?? (event.entryFee ? `Entry fee: ₱${event.entryFee}` : "Open entry · no fee")}</p><TournamentAction disabled={locked} onClick={onView} className="mt-4 w-full">{locked ? "Qualification required" : "View event"}</TournamentAction></div></article>;
}

export default function TournamentCircuitPage() {
  const [chickens, setChickens] = useState<Chicken[]>([]); const [loading, setLoading] = useState(true); const [event, setEvent] = useState<TournamentDefinition | null>(null); const [step, setStep] = useState<CircuitStep>("circuit"); const [fighterId, setFighterId] = useState<string | null>(null);
  useEffect(() => { fetch("/api/chickens").then((res) => res.ok ? res.json() : []).then(setChickens).catch(() => setChickens([])).finally(() => setLoading(false)); }, []);
  const fighter = useMemo(() => chickens.find((chicken) => chicken.id === fighterId), [chickens, fighterId]);
  const open = (next: TournamentDefinition) => { setEvent(next); setFighterId(null); setStep("details"); };
  const context = step === "circuit" ? "Build your name through the regional circuit" : `${event?.name} · ${step === "details" ? "Event dossier" : step === "registration" ? "Fighter selection" : "Entry confirmation"}`;
  if (step === "circuit") return <TournamentShell context={context}><section className="max-w-3xl pt-10"><p className="tournament-kicker">The road to the cup</p><h1 className="tournament-title">Make your name<br />in the pit.</h1><p className="tournament-copy mt-4 max-w-xl">Enter a championship, carry one fighter through the draw, and leave a record that survives every round.</p></section><section className="mt-10 grid gap-4 md:grid-cols-2" aria-label="Available tournaments">{TOURNAMENT_DEFINITIONS.map((item) => <EventPoster key={item.id} event={item} onView={() => open(item)} />)}</section></TournamentShell>;
  if (!event) return null;
  if (step === "details") return <TournamentShell context={context} footer={<><TournamentAction onClick={() => setStep("circuit")}>Back to circuit</TournamentAction><TournamentAction className="tournament-action-primary" onClick={() => setStep("registration")}>Register fighter</TournamentAction></>}><button className="mt-7 text-[10px] font-bold uppercase tracking-[.15em] text-(--color-text-muted) hover:text-(--color-gold-bright)" onClick={() => setStep("circuit")}>← Circuit</button><section className="tournament-panel tournament-panel-strong mt-4 overflow-hidden"><div className="min-h-44 bg-[linear-gradient(90deg,rgba(6,4,2,.84),rgba(20,11,4,.35)),url('/background/arena-background.png')] bg-cover bg-center p-6 sm:p-9"><p className="tournament-kicker">{event.circuit} circuit</p><h1 className="mt-3 font-display text-3xl text-(--color-parchment) sm:text-5xl">{event.name}</h1><p className="mt-2 text-xs uppercase tracking-[.15em] text-(--color-gold-bright)">{event.bracketSize}-bird · {event.tier} · single elimination</p></div><div className="grid gap-px bg-(--color-gold)/15 md:grid-cols-[1.3fr_.7fr]"><div className="bg-[#140d08]/80 p-6"><p className="tournament-kicker">Event details</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="tournament-stat"><label>Entry fee</label><strong>₱{event.entryFee}</strong></div><div className="tournament-stat"><label>Champion</label><strong>{event.championPrize.toLocaleString()}</strong></div></div><div className="mt-5 space-y-2 text-sm text-(--color-text-muted)">{event.rules.map((rule) => <p key={rule} className="border-l border-(--color-gold)/60 pl-3">{rule}</p>)}</div></div><aside className="bg-[#0d0906]/80 p-6"><p className="tournament-kicker">Your history</p><div className="mt-5 space-y-4"><div><p className="text-[10px] uppercase tracking-wider text-(--color-text-muted)">Qualification</p><p className="mt-1 text-sm text-emerald-300">Eligible to enter</p></div><div><p className="text-[10px] uppercase tracking-wider text-(--color-text-muted)">Rule of the night</p><p className="mt-1 text-sm text-(--color-parchment)">One rooster. One run.</p></div></div></aside></div></section></TournamentShell>;
  if (step === "registration") return <TournamentShell context={context} footer={<><TournamentAction onClick={() => setStep("details")}>Back</TournamentAction><TournamentAction className="tournament-action-primary" disabled={!fighter} onClick={() => setStep("confirm")}>{fighter ? `Register ${fighter.name}` : "Select a fighter"}</TournamentAction></>}><section className="mt-8"><p className="tournament-kicker">{event.name} · {event.bracketSize}-bird · {event.tier}</p><h1 className="mt-2 font-display text-3xl text-(--color-parchment)">Select your fighter</h1><p className="tournament-copy mt-2">Choose the rooster who will carry your colors through the championship.</p></section>{loading ? <p className="mt-10 text-sm text-(--color-text-muted)">Opening the coop roster…</p> : <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{chickens.map((chicken) => { const reason = eligibility(chicken); const selected = chicken.id === fighterId; return <button key={chicken.id} disabled={Boolean(reason)} onClick={() => setFighterId(chicken.id)} className={`tournament-fighter p-4 text-left ${selected ? "tournament-fighter-selected" : ""} ${reason ? "cursor-not-allowed opacity-45 grayscale" : ""}`}><div className="flex items-center gap-3"><ChickenThumbnail chicken={chicken} className="h-16 w-16" /><div className="min-w-0"><h2 className="truncate font-display text-lg text-(--color-parchment)">{chicken.name}</h2><p className="text-[10px] uppercase tracking-wide text-(--color-text-muted)">{chicken.fightingStyle} · {chicken.record.wins}W–{chicken.record.losses}L</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="tournament-stat"><label>Condition</label><strong>{chicken.condition ?? 100}%</strong></div><div className="tournament-stat"><label>Health</label><strong>{chicken.health}%</strong></div></div><p className={`mt-3 text-[10px] font-bold uppercase tracking-[.14em] ${reason ? "text-red-300" : "text-emerald-300"}`}>{reason ?? (selected ? "Selected" : "Eligible · ready")}</p></button>; })}</section>}</TournamentShell>;
  return <TournamentShell context={context} footer={<><TournamentAction onClick={() => setStep("registration")}>Change fighter</TournamentAction><Link href={`/tournament/${fighter?.id}?event=${event.id}`} className="tournament-action tournament-action-primary">Confirm entry</Link></>}><section className="tournament-panel tournament-panel-strong mx-auto mt-16 max-w-2xl p-7 text-center sm:p-10"><p className="tournament-kicker">Final call</p><h1 className="mt-4 font-display text-3xl text-(--color-parchment)">Register {fighter?.name}?</h1><p className="tournament-copy mx-auto mt-4 max-w-lg">Once the draw begins, this fighter cannot be replaced. Current condition carries into the event, injuries persist, and elimination ends the run.</p>{fighter && <div className="mt-7 flex justify-center"><div className="tournament-fighter flex items-center gap-3 p-3"><ChickenThumbnail chicken={fighter} className="h-16 w-16" /><div className="text-left"><p className="font-display text-lg">{fighter.name}</p><p className="text-xs text-(--color-text-muted)">{fighter.fightingStyle} · {fighter.condition ?? 100}% condition</p></div></div></div>}</section></TournamentShell>;
}
