export type FacilityErrorCode =
  | "FACILITY_NOT_FOUND"
  | "FACILITY_NOT_OWNED"
  | "PROGRAM_LOCKED"
  | "PROGRAM_NOT_FOUND"
  | "FACILITY_CAPACITY_FULL"
  | "CHICKEN_NOT_FOUND"
  | "CHICKEN_NOT_OWNED"
  | "CHICKEN_ALREADY_TRAINING"
  | "CHICKEN_NOT_ELIGIBLE"
  | "INSUFFICIENT_ENERGY"
  | "TRAINING_LIMIT_REACHED"
  | "FACILITY_MAX_LEVEL"
  | "INSUFFICIENT_RESOURCES"
  | "SESSION_NOT_FOUND"
  | "SESSION_NOT_ACTIVE"
  | "INVALID_CATEGORY";

const STATUS_BY_CODE: Record<FacilityErrorCode, number> = {
  FACILITY_NOT_FOUND: 404,
  FACILITY_NOT_OWNED: 404,
  PROGRAM_LOCKED: 400,
  PROGRAM_NOT_FOUND: 400,
  FACILITY_CAPACITY_FULL: 400,
  CHICKEN_NOT_FOUND: 404,
  CHICKEN_NOT_OWNED: 404,
  CHICKEN_ALREADY_TRAINING: 400,
  CHICKEN_NOT_ELIGIBLE: 400,
  INSUFFICIENT_ENERGY: 400,
  TRAINING_LIMIT_REACHED: 400,
  FACILITY_MAX_LEVEL: 400,
  INSUFFICIENT_RESOURCES: 400,
  SESSION_NOT_FOUND: 404,
  SESSION_NOT_ACTIVE: 400,
  INVALID_CATEGORY: 400,
};

export class FacilityError extends Error {
  code: FacilityErrorCode;
  status: number;

  constructor(code: FacilityErrorCode) {
    super(code);
    this.code = code;
    this.status = STATUS_BY_CODE[code];
  }
}
