import type { Facility } from "@prisma/client";
import { prisma } from "../db";
import { canTrain } from "../growth";
import { isTrainingLocked } from "../medical/rehab";
import { INTENSITY_MULTIPLIERS } from "../training/intensity";
import { canAffordTrainingPoints, defaultTrainingState } from "../training/limits";
import { rollTrainingPotential } from "../training/potential";
import { resolveTrainingSession } from "../training/resolver";
import { defaultRoosterTrainingState } from "../training/state";
import { getOrCreateRoosterTraining } from "../training/service";
import { normalizeIntensity } from "../training/calculation";
import type { TrainingPreview, TrainingSessionIntent } from "../training/types";
import { previewTrainingSession } from "../training/preview";
import { TRAINING_GYM_LEVELS, TRAINING_GYM_MAX_LEVEL, TRAINING_GYM_UPGRADES, TRAINING_PROGRAMS, isProgramUnlocked } from "./config";
import { FacilityError } from "./errors";
import type { FacilityType, ProgramId } from "./types";
import { TRAINING_CATEGORIES, type Chicken, type GrowthStage, type InjuryRecord, type RoosterTrainingState, type StatBlock, type TrainingCategory, type TrainingIntensity, type TrainingState } from "../types";

const TRAINING_GYM:FacilityType="TRAINING_GYM";
export async function getOrCreateTrainingGym(playerId:string):Promise<Facility>{const found=await prisma.facility.findUnique({where:{playerId_type:{playerId,type:TRAINING_GYM}}});return found??prisma.facility.create({data:{playerId,type:TRAINING_GYM,level:1}});}
export function facilityView(facility:Facility){const c=TRAINING_GYM_LEVELS[facility.level];return{id:facility.id,type:facility.type,level:facility.level,...c,unlockedPrograms:c.programs};}
function resolveCategory(programId:ProgramId,requested?:TrainingCategory):TrainingCategory{const p=TRAINING_PROGRAMS[programId];if(p.category!=="custom")return p.category;if(!requested||!TRAINING_CATEGORIES.includes(requested))throw new FacilityError("INVALID_CATEGORY");return requested;}
function stateFromRow(row:{physicalXP:number;combatXP:number;tacticalXP:number;disciplineXP:number;recoveryXP:number;effortSpent:unknown;trainingPotential:unknown;discovered:unknown;traits:unknown;breakthroughs:unknown;traitProgress:unknown;specializationProgress:unknown}):RoosterTrainingState{return{physicalXP:row.physicalXP,combatXP:row.combatXP,tacticalXP:row.tacticalXP,disciplineXP:row.disciplineXP,recoveryXP:row.recoveryXP,effortSpent:row.effortSpent as StatBlock,trainingPotential:row.trainingPotential as StatBlock,discovered:row.discovered as RoosterTrainingState["discovered"],traits:row.traits as RoosterTrainingState["traits"],breakthroughs:row.breakthroughs as RoosterTrainingState["breakthroughs"],traitProgress:(row.traitProgress as Record<string,number>)??{},specializationProgress:(row.specializationProgress as Record<string,number>)??{}};}
function sessionCosts(programId:ProgramId,intensity:ReturnType<typeof normalizeIntensity>){const p=TRAINING_PROGRAMS[programId],m=INTENSITY_MULTIPLIERS[intensity];return{energyCost:Math.ceil(p.energyCost*m.energy),fatigueCost:Math.ceil(p.fatigueCost*m.fatigue),stressCost:Math.round(p.stressCost*m.stress),trainingPointCost:p.trainingPointCost};}

export async function startTrainingSession(playerId:string,chickenId:string,programId:ProgramId,category?:TrainingCategory,intensityInput?:TrainingIntensity){
  const program=TRAINING_PROGRAMS[programId];if(!program)throw new FacilityError("PROGRAM_NOT_FOUND");
  const intensity=normalizeIntensity(intensityInput);if(!["light","normal","hard","extreme"].includes(intensity))throw new FacilityError("INVALID_INTENSITY");
  const facility=await getOrCreateTrainingGym(playerId);await claimExpiredSessions(playerId);if(!isProgramUnlocked(programId,facility.level))throw new FacilityError("PROGRAM_LOCKED");
  const resolvedCategory=resolveCategory(programId,category),costs=sessionCosts(programId,intensity);
  return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Facility" WHERE id = ${facility.id} FOR UPDATE`;const chicken=await tx.chicken.findUnique({where:{id:chickenId}});if(!chicken)throw new FacilityError("CHICKEN_NOT_FOUND");if(chicken.playerId!==playerId)throw new FacilityError("CHICKEN_NOT_OWNED");if(!canTrain(chicken.growthStage as GrowthStage))throw new FacilityError("CHICKEN_NOT_ELIGIBLE");if(chicken.energy<costs.energyCost)throw new FacilityError("INSUFFICIENT_ENERGY");if((intensity==="hard"||intensity==="extreme"||programId==="HARD_SPARRING")&&chicken.condition<25)throw new FacilityError("CONDITION_TOO_LOW");
    const injuries=((chicken.injuries as unknown as InjuryRecord[])??[]).filter(i=>i.permanent||i.recoveryRemaining>0);if(isTrainingLocked(injuries,resolvedCategory))throw new FacilityError("TRAINING_LOCKED_BY_INJURY");const trainingState=(chicken.trainingState as unknown as TrainingState)??defaultTrainingState();if(!canAffordTrainingPoints(trainingState,costs.trainingPointCost))throw new FacilityError("TRAINING_LIMIT_REACHED");
    if(await tx.trainingSession.findFirst({where:{chickenId,status:"ACTIVE"}}))throw new FacilityError("CHICKEN_ALREADY_TRAINING");if(await tx.trainingSession.count({where:{facilityId:facility.id,status:"ACTIVE"}})>=TRAINING_GYM_LEVELS[facility.level].capacity)throw new FacilityError("FACILITY_CAPACITY_FULL");
    if(!await tx.roosterTraining.findUnique({where:{chickenId}})){const fresh=defaultRoosterTrainingState(rollTrainingPotential(chicken.iv as StatBlock,Math.random));await tx.roosterTraining.create({data:{chickenId,physicalXP:0,combatXP:0,tacticalXP:0,disciplineXP:0,recoveryXP:0,effortSpent:fresh.effortSpent as object,trainingPotential:fresh.trainingPotential as object,discovered:{},traits:[],breakthroughs:[],traitProgress:{},specializationProgress:{}}});}
    return tx.trainingSession.create({data:{playerId,chickenId,facilityId:facility.id,programId,category:resolvedCategory,intensity,status:"ACTIVE",durationMinutes:program.durationMinutes,...costs,workload:program.workload}});
  });
}
export async function cancelTrainingSession(playerId:string,sessionId:string){const s=await prisma.trainingSession.findUnique({where:{id:sessionId}});if(!s||s.playerId!==playerId)throw new FacilityError("SESSION_NOT_FOUND");if(s.status!=="ACTIVE")throw new FacilityError("SESSION_NOT_ACTIVE");return prisma.trainingSession.update({where:{id:sessionId},data:{status:"CANCELLED",completedAt:new Date()}});}

export async function claimExpiredSessions(playerId:string):Promise<void>{
  const candidates=await prisma.trainingSession.findMany({where:{playerId,status:"ACTIVE"}});for(const candidate of candidates){if(Date.now()<candidate.startedAt.getTime()+candidate.durationMinutes*60000)continue;
    await prisma.$transaction(async tx=>{const locked=await tx.$queryRaw<Array<{status:string}>>`SELECT status FROM "TrainingSession" WHERE id = ${candidate.id} FOR UPDATE`;if(!locked[0]||locked[0].status!=="ACTIVE")return;await tx.$queryRaw`SELECT id FROM "Chicken" WHERE id = ${candidate.chickenId} FOR UPDATE`;const row=await tx.chicken.findUnique({where:{id:candidate.chickenId}});if(!row)return;
      const program=TRAINING_PROGRAMS[candidate.programId as ProgramId];if(!program)return;const facility=await tx.facility.findUnique({where:{id:candidate.facilityId}});const facilityConfig=TRAINING_GYM_LEVELS[facility?.level??1];let rt=await tx.roosterTraining.findUnique({where:{chickenId:candidate.chickenId}});if(!rt){const fresh=defaultRoosterTrainingState(rollTrainingPotential(row.iv as StatBlock,Math.random));rt=await tx.roosterTraining.create({data:{chickenId:candidate.chickenId,physicalXP:fresh.physicalXP,combatXP:fresh.combatXP,tacticalXP:fresh.tacticalXP,disciplineXP:fresh.disciplineXP,recoveryXP:fresh.recoveryXP,effortSpent:fresh.effortSpent as object,trainingPotential:fresh.trainingPotential as object,discovered:fresh.discovered as object,traits:fresh.traits as object,breakthroughs:fresh.breakthroughs as object,traitProgress:fresh.traitProgress as object,specializationProgress:fresh.specializationProgress as object}});}
      const session:TrainingSessionIntent={id:candidate.id,chickenId:candidate.chickenId,programId:candidate.programId as ProgramId,category:candidate.category as TrainingCategory,intensity:normalizeIntensity(candidate.intensity),startedAt:candidate.startedAt,durationMinutes:candidate.durationMinutes,energyCost:candidate.energyCost,fatigueCost:candidate.fatigueCost,stressCost:candidate.stressCost,trainingPointCost:candidate.trainingPointCost};
      const result=resolveTrainingSession({chicken:row as unknown as Chicken,session,program,facility:facilityConfig,trainingState:(row.trainingState as unknown as TrainingState)??defaultTrainingState(),roosterTraining:stateFromRow(rt),rng:Math.random});
      await tx.chicken.update({where:{id:candidate.chickenId},data:{ev:result.nextEv as object,energy:result.nextEnergy,trainingState:result.nextTrainingState as object,experience:result.nextExperience as object,behavior:result.nextBehavior as object,traits:result.nextTraits as object,condition:result.nextCondition,stress:result.nextStress,battleHardening:result.nextBattleHardening,injuries:result.nextInjuries as object,injured:result.nextInjuries.some(i=>!i.permanent&&i.recoveryRemaining>0)}});
      await tx.roosterTraining.update({where:{chickenId:candidate.chickenId},data:{physicalXP:Math.round(result.nextRoosterTraining.physicalXP),combatXP:Math.round(result.nextRoosterTraining.combatXP),tacticalXP:Math.round(result.nextRoosterTraining.tacticalXP),disciplineXP:Math.round(result.nextRoosterTraining.disciplineXP),recoveryXP:Math.round(result.nextRoosterTraining.recoveryXP),effortSpent:result.nextRoosterTraining.effortSpent as object,discovered:result.nextRoosterTraining.discovered as object,traits:result.nextRoosterTraining.traits as object,breakthroughs:result.nextRoosterTraining.breakthroughs as object,traitProgress:result.nextRoosterTraining.traitProgress as object,specializationProgress:result.nextRoosterTraining.specializationProgress as object}});
      await tx.trainingSession.update({where:{id:candidate.id},data:{status:"COMPLETED",completedAt:new Date(result.persistedResult.completedAt),adaptationResult:result.persistedResult as object}});
    });
  }
}

export async function previewTrainingForChicken(playerId:string,chickenId:string,programId:ProgramId,category?:TrainingCategory,intensityInput?:TrainingIntensity):Promise<TrainingPreview>{const program=TRAINING_PROGRAMS[programId];if(!program)throw new FacilityError("PROGRAM_NOT_FOUND");const facility=await getOrCreateTrainingGym(playerId);if(!isProgramUnlocked(programId,facility.level))throw new FacilityError("PROGRAM_LOCKED");const chicken=await prisma.chicken.findUnique({where:{id:chickenId}});if(!chicken||chicken.playerId!==playerId)throw new FacilityError("CHICKEN_NOT_FOUND");const intensity=normalizeIntensity(intensityInput),costs=sessionCosts(programId,intensity),resolvedCategory=resolveCategory(programId,category);const rt=await getOrCreateRoosterTraining(chickenId,chicken.iv as StatBlock);const session:TrainingSessionIntent={id:"preview",chickenId,programId,category:resolvedCategory,intensity,startedAt:new Date(),durationMinutes:program.durationMinutes,...costs};return previewTrainingSession({chicken:chicken as unknown as Chicken,session,program,facility:TRAINING_GYM_LEVELS[facility.level],trainingState:(chicken.trainingState as unknown as TrainingState)??defaultTrainingState(),roosterTraining:rt});}

export async function upgradeFacility(playerId:string,facilityId:string){return prisma.$transaction(async tx=>{const f=await tx.facility.findUnique({where:{id:facilityId}});if(!f)throw new FacilityError("FACILITY_NOT_FOUND");if(f.playerId!==playerId)throw new FacilityError("FACILITY_NOT_OWNED");if(f.level>=TRAINING_GYM_MAX_LEVEL)throw new FacilityError("FACILITY_MAX_LEVEL");const next=f.level+1,cost=TRAINING_GYM_UPGRADES[next].cost,p=await tx.player.findUnique({where:{id:playerId}});if(!p||p.credits<cost)throw new FacilityError("INSUFFICIENT_RESOURCES");await tx.player.update({where:{id:playerId},data:{credits:p.credits-cost}});return tx.facility.update({where:{id:facilityId},data:{level:next}});});}
